planner_server:
  ros__parameters:
    use_sim_time: True
    expected_planner_frequency: 20.0

    # Planner plugins
    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.10
      use_astar: false
      allow_unknown: true


global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: True

      # Frames
      global_frame: map
      robot_base_frame: robot_base_footprint

      # Update settings
      update_frequency: 1.0
      publish_frequency: 1.0
      always_send_full_costmap: True

      # Costmap geometry
      resolution: 0.05
      robot_radius: 0.27
      track_unknown_space: true

      # Layers
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan

        scan:
          topic: /scan
          data_type: "LaserScan"
          marking: True
          clearing: True
          max_obstacle_height: 2.0
          obstacle_max_range: 15.0
          obstacle_min_range: 0.1
          raytrace_max_range: 15.0
          raytrace_min_range: 0.1

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 2.0
        inflation_radius: 0.34